# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_envelope_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='transaction_velocity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
