# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelopes', '0001_initial'),
        ('accounts', '0003_auto_20160927_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envelopes.Envelope')),
            ],
        ),
    ]
